create or replace FUNCTION F_MEDIAEXPOSURERATING
       (P_DATE IN TIMESTAMP)
       RETURN NUMBER IS output NUMBER(10);

       BEGIN
              SELECT
                     SUM((TV_POSITIVE + RADIO_POSITIVE + NEWSPAPER_POSITIVE + INTERNET_POSITIVE + WEEKLY_MAGAZINE_POSITIVE) - (TV_NEGATIVE + RADIO_NEGATIVE + NEWSPAPER_NEGATIVE + INTERNET_NEGATIVE + WEEKLY_MAGAZINE_NEGATIVE)) INTO output
              FROM CONTRACT_MEDIA_EXPR
              WHERE
                     TO_DATE(CONTRACT_MEDIA_EXPR.EXPOSUREDATE, 'DD-MM-YYYY') = TO_DATE(TO_CHAR(P_DATE, 'YYYY-MM-DD'), 'YYYY-MM-DD');

              RETURN output;

              EXCEPTION WHEN NO_DATA_FOUND THEN
                 RETURN(0);

       END F_MEDIAEXPOSURERATING;