SELECT ITEMS.ID as ItemsID, SUM(ORDERITEMS."NUMBER", 'order_by_clause'), SUM(ITEMS.NUMBER_OF_COUPONS), SUM(ORDERITEMS."NUMBER")*SUM(ITEMS.NUMBER_OF_COUPONS) AS totalCoupons
FROM ORDERS
  JOIN ORDERITEMS
    ON ORDERS.ID = ORDERITEMS.ORDERS_ID
  JOIN STUDENTS
    ON ORDERS.STUDENTS_ID = STUDENTS.ID
  JOIN ITEMS
    ON ORDERITEMS.ITEMS_ID = ITEMS.ID
WHERE
  STUDENTS.ID = 1
GROUP BY ITEMS.ID;