SELECT DISTINCT STUDENTS.ID, SUM(ITEMS.NUMBER_OF_COUPONS * ORDERITEMS."NUMBER") AS TOTAL
  FROM ORDERS
  JOIN ORDERITEMS
    ON ORDERS.ID = ORDERITEMS.ORDERS_ID
  JOIN STUDENTS
    ON ORDERS.STUDENTS_ID = STUDENTS.ID
  JOIN ITEMS
    ON ORDERITEMS.ITEMS_ID = ITEMS.ID
WHERE
  STUDENTS.ID = 1
GROUP BY STUDENTS.ID;