-- view: Waiter Ordered Items
-- which orders and orderitems are taken at what date, week, day and by which
-- waiter.
-- get the name of the event using a function(f_eventname). If not found return: 'Unknown'

-- view columns: event, waiter, order_id, order_item, type_of_consumption, date, week, day

SELECT
  F_GETEVENT(ORDERS.DATEORDER) AS EVENT,
  STUDENTS.NAME AS WAITER,
  ORDERS.ID AS ORDER_ID,
  ITEMS.NAME AS ORDER_ITEM,
  ITEMS.TYPE AS TYPE_OF_CONSUMPTION,
  ORDERS.DATEORDER AS "DATE",
  to_number(to_char(ORDERS.DATEORDER, 'WW')) AS WEEK,
  to_char(ORDERS.DATEORDER, 'DAY') AS DAY
FROM
  ORDERS
JOIN ORDERITEMS
  ON ORDERS.ID = ORDERITEMS.ORDERS_ID
JOIN ITEMS
  ON ORDERITEMS.ITEMS_ID = ITEMS.ID
JOIN BARS
  ON ORDERS.BARS_ID = BARS.ID
JOIN PROPRIETOR_BARS
  ON BARS.ID = PROPRIETOR_BARS.BARS_ID
JOIN SCHEDULES
  ON PROPRIETOR_BARS.ID = SCHEDULES.PROPRIETOR_BARS_ID
JOIN APPLIES
  ON SCHEDULES.ID = APPLIES.SCHEDULES_ID
JOIN STUDENTS
  ON ORDERS.STUDENTS_ID = STUDENTS.ID AND APPLIES.STUDENTS_ID = STUDENTS.ID
JOIN EVENTS
  ON SCHEDULES.EVENTS_ID = EVENTS.ID
WHERE
  APPLIES.CAPACITY = 'WAITER';