SELECT
  STUDENTS.ID AS STUDENT_ID,
  EVENTS.ID AS EVENT_ID,
  (2.5 * SUM(SUB1.TOTALCOUPONS) * 1.00 * 0.04) AS BONUS_AMOUNT,
  SUM(SUB1.TOTALCOUPONS) AS COLLECTED_COUPONS
FROM
  STUDENTS
  JOIN (SELECT
          ITEMS.ID AS ITEM_ID,
          ORDERS.STUDENTS_ID AS STUDENTS_ID,
          SUM(ORDERITEMS."NUMBER") AS TOTALORDERED,
          (SUM(ORDERITEMS."NUMBER") * ITEMS.NUMBER_OF_COUPONS) AS TOTALCOUPONS
        FROM
          ORDERITEMS
          JOIN ORDERS
            ON ORDERITEMS.ORDERS_ID = ORDERS.ID
          JOIN ITEMS
            ON ORDERITEMS.ITEMS_ID = ITEMS.ID
        GROUP BY ITEMS.ID, ITEMS.NUMBER_OF_COUPONS, ORDERS.STUDENTS_ID) SUB1
    ON STUDENTS_ID = STUDENTS.ID
  JOIN APPLIES
    ON STUDENTS.ID = APPLIES.STUDENTS_ID
  JOIN SCHEDULES
    ON APPLIES.SCHEDULES_ID = SCHEDULES.ID
  JOIN EVENTS
    ON SCHEDULES.EVENTS_ID = EVENTS.ID
WHERE
  APPLIES.STATUS = 'PLANNED' AND
  APPLIES.CAPACITY != 'COUPON_SELLER' AND
  EVENTS.ID = 1
GROUP BY EVENTS.ID, STUDENTS.ID